package lapr.project.ui.CreateEvent;

//import java.util.ArrayList;
//import java.util.List;
//import javax.swing.DefaultListModel;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import lapr.project.controller.CreateEventController;
import lapr.project.model.*;
import lapr.project.ui.MainWindow;
import lapr.project.utils.Date;
import lapr.project.utils.EmptySpaceException;
import lapr.project.utils.InvalidDayException;
import lapr.project.utils.InvalidMonthException;
import lapr.project.utils.InvalidYearException;

/**
 *
 * @author 1160590_1160795_1160844_1161241_1162109
 */
public class CreateEventMain extends javax.swing.JFrame implements Serializable {

    private FairCenter fc;
    private User u;
    private List<String> organizerListEvent;
    private List<String> userList;

    CreateEventController controller;

    //private final DefaultListModel userModel = new DefaultListModel();
    /**
     * Creates new form CreateEventMain
     *
     * @param fc
     * @param u
     */
    public CreateEventMain(FairCenter fc, User u) {
        this.fc = fc;
        this.u = u;
        this.organizerListEvent = new ArrayList<>();
        this.userList = controller.getUserList();
        controller = new CreateEventController(fc);
        initComponents();
        jComboBox1.addItem("Congress");
        jComboBox1.addItem("Exhibition");
        AbstractListModel model = new javax.swing.AbstractListModel() {

            @Override
            public int getSize() {
                return userList.size();
            }

            @Override
            public Object getElementAt(int j) {
                return userList.get(j);
            }
        };
        OrganizerList.setModel(model);
        jScrollPane1.setViewportView(OrganizerList);
        AbstractListModel model1 = new javax.swing.AbstractListModel() {

            @Override
            public int getSize() {
                return organizerListEvent.size();
            }

            @Override
            public Object getElementAt(int j) {
                return organizerListEvent.get(j);
            }
        };
        ChosenOrganizerList.setModel(model1);
        jScrollPane2.setViewportView(ChosenOrganizerList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        TypeLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        TitleLabel = new javax.swing.JLabel();
        TitleInputTextField = new javax.swing.JTextField();
        DescriptionLabel = new javax.swing.JLabel();
        StartDateLabel = new javax.swing.JLabel();
        StartDateInputTextField = new javax.swing.JTextField();
        EndDateLabel = new javax.swing.JLabel();
        EndDateInputTextField = new javax.swing.JTextField();
        StartSubDateLabel = new javax.swing.JLabel();
        StartSubDateInputTextField = new javax.swing.JTextField();
        EndSubDateLabel = new javax.swing.JLabel();
        EndSubDateInputTextField = new javax.swing.JTextField();
        OkButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        DescriptionInputTextField = new javax.swing.JTextField();
        PlaceLabel = new javax.swing.JLabel();
        PlaceInputTextField = new javax.swing.JTextField();
        DataFormatNoteLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrganizerList = new javax.swing.JList<>();
        AddOrganizerButton = new javax.swing.JButton();
        RemoveOrganizer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ChosenOrganizerList = new javax.swing.JList<>();
        OrganizerNoteLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TypeLabel.setText("Type");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Congress", "Exhibition" }));

        TitleLabel.setText("Title");

        DescriptionLabel.setText("Description");

        StartDateLabel.setText("Start Date");

        EndDateLabel.setText("End Date");

        StartSubDateLabel.setText("Start Submission Date");

        EndSubDateLabel.setText("End Submission Date ");

        OkButton.setText("Create");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        PlaceLabel.setText("Place");

        DataFormatNoteLabel.setText("Insert all date's in the yyyy/mm/dd format.");

        jScrollPane1.setViewportView(OrganizerList);

        AddOrganizerButton.setText("Add ->");
        AddOrganizerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOrganizerButtonActionPerformed(evt);
            }
        });

        RemoveOrganizer.setText("<- Remove");
        RemoveOrganizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveOrganizerActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(ChosenOrganizerList);

        OrganizerNoteLabel.setText("Select two or more organizers.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescriptionLabel)
                    .addComponent(TitleLabel)
                    .addComponent(TypeLabel)
                    .addComponent(PlaceLabel)
                    .addComponent(DataFormatNoteLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EndSubDateLabel)
                            .addComponent(StartSubDateLabel)
                            .addComponent(EndDateLabel)
                            .addComponent(StartDateLabel))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartDateInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndDateInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StartSubDateInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndSubDateInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlaceInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescriptionInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TitleInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RemoveOrganizer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddOrganizerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(OrganizerNoteLabel))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OkButton)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeLabel)
                    .addComponent(OrganizerNoteLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TitleInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TitleLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DescriptionInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DescriptionLabel))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlaceInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PlaceLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(StartDateInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StartDateLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EndDateLabel)
                                    .addComponent(EndDateInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(StartSubDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StartSubDateInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EndSubDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EndSubDateInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(AddOrganizerButton)
                                .addGap(49, 49, 49)
                                .addComponent(RemoveOrganizer))))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(DataFormatNoteLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(OkButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MainWindow mainWindow = new MainWindow(fc, u);
        mainWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        String type = jComboBox1.getSelectedItem().toString();

        try {
            String place = PlaceInputTextField.getText();
            controller.validateString(place, "place");
            String submissionStartDate = StartSubDateInputTextField.getText();
            controller.validateDay(submissionStartDate, "submission start date");
            controller.validateMonth(submissionStartDate, "submission start date");
            controller.validateYear(submissionStartDate, "submission start date");
            String description = DescriptionInputTextField.getText();
            controller.validateString(description, "description");
            String endDate = EndDateInputTextField.getText();
            controller.validateDay(endDate, "end date");
            controller.validateMonth(endDate, "end date");
            controller.validateYear(endDate, "end date");
            String startDate = StartDateInputTextField.getText();
            controller.validateDay(startDate, "start date");
            controller.validateMonth(startDate, "start date");
            controller.validateYear(startDate, "start date");
            String title = TitleInputTextField.getText();
            controller.validateString(title, "title");
            String submissionEndDate = EndSubDateInputTextField.getText();
            controller.validateDay(submissionEndDate, "submission end date");
            controller.validateMonth(submissionEndDate, "submission end date");
            controller.validateYear(submissionEndDate, "submission end date");
            if (type.equals("Congress")) {
                controller.setDataCongress(title, description, place, startDate, endDate, submissionStartDate, submissionEndDate, organizerListEvent);
                JOptionPane.showMessageDialog(CreateEventMain.this, "Congress created with success", "SUCCESS", JOptionPane.OK_OPTION);
            } else if (type.equals("Exhibition")) {
                controller.setDataExhibition(title, description, place, startDate, endDate, submissionStartDate, submissionEndDate, organizerListEvent);
                JOptionPane.showMessageDialog(CreateEventMain.this, "Exhibition created with success", "SUCCESS", JOptionPane.OK_OPTION);
            }
        } catch (EmptySpaceException | InvalidDayException | InvalidMonthException | InvalidYearException e) {
            JOptionPane.showMessageDialog(CreateEventMain.this, e.getMessage());
        }

    }//GEN-LAST:event_OkButtonActionPerformed

    private void AddOrganizerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOrganizerButtonActionPerformed
        String user = OrganizerList.getSelectedValue();
        organizerListEvent.add(user);
        userList.remove(user);
    }//GEN-LAST:event_AddOrganizerButtonActionPerformed

    private void RemoveOrganizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveOrganizerActionPerformed
        String organizer = ChosenOrganizerList.getSelectedValue();
        userList.add(organizer);
        organizerListEvent.remove(organizer);
    }//GEN-LAST:event_RemoveOrganizerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrganizerButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JList<String> ChosenOrganizerList;
    private javax.swing.JLabel DataFormatNoteLabel;
    private javax.swing.JTextField DescriptionInputTextField;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextField EndDateInputTextField;
    private javax.swing.JLabel EndDateLabel;
    private javax.swing.JTextField EndSubDateInputTextField;
    private javax.swing.JLabel EndSubDateLabel;
    private javax.swing.JButton OkButton;
    private javax.swing.JList<String> OrganizerList;
    private javax.swing.JLabel OrganizerNoteLabel;
    private javax.swing.JTextField PlaceInputTextField;
    private javax.swing.JLabel PlaceLabel;
    private javax.swing.JButton RemoveOrganizer;
    private javax.swing.JTextField StartDateInputTextField;
    private javax.swing.JLabel StartDateLabel;
    private javax.swing.JTextField StartSubDateInputTextField;
    private javax.swing.JLabel StartSubDateLabel;
    private javax.swing.JTextField TitleInputTextField;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
